assetic:
  filters:
    cssembed:
      jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
    yui_js:
      jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
    lessphp:
      file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
      apply_to: "\.less$"
#    uglifyjs2:
#        bin: /usr/local/bin/uglifyjs
  assets:
    jquery_js:
        inputs:
            - '%kernel.root_dir%/app/Resources/public/js/vendor/jquery.js'
        output: static/js/jquery.js
        filters: [?yui_js]

    bootstrap_js:
        inputs:
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/transition.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/alert.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/modal.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/dropdown.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/scrollspy.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/tab.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/tooltip.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/popover.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/button.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/collapse.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/carousel.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/affix.js'
        output: static/js/bootstrap.js
        filters: [?yui_js]
    bootstrap_less:
        inputs:
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less'
        output: static/js/bootstrap.css
        filters: [lessphp,cssembed]
